name: rag-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - langchain>=0.1.0
    - langchain-community>=0.0.20
    - qdrant-client>=1.7.0
    - sentence-transformers>=2.2.0
    - transformers>=4.30.0
    - torch>=2.0.0
    - pypdf>=3.0.0
    - unstructured>=0.10.0
    - tiktoken>=0.5.0